name: aae364
channels:
  - conda-forge
  - defaults
dependencies:
  - pip
  - matplotlib
  - numpy
  - scipy
  - sympy
  - control
  - pytest
  - pydot
  - librosa
  - sympy
  - opencv
  - pyulog
  - pip:
    - casadi
    - sysid
